### PR TITLE
Feat/scroll page

### PR DESCRIPTION
**Pull request by xavierlefevre**

### CODE REVIEW

**Comment by RichardLitt** [comment]
@xavierlefevre Can you explain what this was, and why it was closed? I'm curious. :)

**Comment by xavierlefevre** [comment]
@RichardLitt :D Nice to witness your curiosity. It was a mistake, I wanted to open a PR on our fork.

We forked your nice feature for the sake of our project, because we needed two things:
- Being able to display copilot only on some part of the screen, below a header on which we don't want copilot to show for instance
- Having steps on elements not visible at first because inside a scrollview

We should have a good result soon enough. We planned on opening a PR later when it's working well :) What do you think?

**Comment by RichardLitt** [comment]
I think those might be good features - thanks for explaining! I'd encourage you to open issues for both of those, as the other maintainers can weigh in on whether a PR would work, and we might be able to help with the implementation. 

Thanks for explaining! Glad you like this.

**Comment by xavierlefevre** [comment]
Alright, will do, I put that on my todo for the week!

Happy if it helps others!!

**Pull request closed without merging**
