### PR TITLE
add unregisterStep function to WrappedComponent

### PR DESCRIPTION
**Pull request by bemazo**
with this it is possible to delete steps by the WrappedComponent

`this.props.unregisterStep('step_name');`

### CODE REVIEW

**Comment by mohebifar** [comment]
Thanks for the PR.

I think if we add `unregisterStep`, we should add `registerStep` as well. I prefer to have the `CopilotStep`s controlling the registered steps. How about adding a new prop (`active`) to `CopilotStep` that indicates whether the step is active or not?

```jsx
<CopilotStep active={false | true} text="Hello!" order={1} name="hello">
```

**Comment by bemazo** [comment]
an active flag will be perfect, than it can be handled by a state variable

**Comment by RichardLitt** [comment]
@bemazo Would you be willing to adjust this PR to add an active flag?

**Comment by ohtangza** [comment]
The proposed active flag looks awesome!

**Comment by mohebifar** [comment]
Closing this in favor of #58.

**Pull request closed without merging**
